version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    networks:
      api-user-network:
    ports:
      - 3308:3306

  user-api-service:
    container_name: user-api-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
    networks:
      api-user-network:
    restart: on-failure


networks:
  api-user-network:
